### PR TITLE
feat: Add external profile to the api

### PR DESCRIPTION
**Pull request by dooven**
##### Summary
- Add external profile to the api
- Also added the `Twter` field to the `ProfileResponse`

##### Component Name
area/backend

### CODE REVIEW

**Comment by prologic** [comment]
@dooven I _would_ match the changes made in https://github.com/jointwt/twtxt/commit/8ac0380a5c5561fe0ae164864653a8c06c3a546e where we use the form `/external/:slug/:nick` turns out using query params isn't that great when you want to also combine paging.

**Comment by dooven** [comment]
> @dooven I _would_ match the changes made in [8ac0380](https://github.com/jointwt/twtxt/commit/8ac0380a5c5561fe0ae164864653a8c06c3a546e) where we use the form `/external/:slug/:nick` turns out using query params isn't that great when you want to also combine paging.

Sounds good. My concern is that the API don't have a hold of the slugified URL, since the `Twter` struct only contains the nick & url. Do you think it'll be a good idea to add a slug field in the Twter struct?

**Comment by prologic** [comment]
If we shove the Slug into the `Twter` struct, then I can remove this `slugs` `sync.Map` data structure. Perhaps this is the better option? Making the consumer/client perform this might lead to inconsistencies? The only downside is that the cache structure would break and have to be rebuilt, since we've done this a number of times now, I would also suggest we stick a `Version` field in the `Cache` struct so we can programatically determine if:

- We need to ignore the cache on disk and start over
- Of if we can upgrade the structure on disk to the new one in code

**Comment by dooven** [comment]
Yeah having the a version so that our cache gets some awareness if the structure got updated is nice! Just wondering if you can take the work for this adding the version :sweat_smile: : Im not so sure how to how to implement it

**Comment by prologic** [comment]
> Just wondering if you can take the work for this adding the version 😅 : Im not so sure how to implement it

I'll have a crack at it!  You carry on with the rest of this PR :D

**Comment by dooven** [comment]
This commit uses slug to get the external profile https://github.com/jointwt/twtxt/pull/168/commits/b246a815b6ce464b4876d3b24614cedc3ee31053

**Review by prologic — APPROVED** [review]

**Pull request merged**
