### PR TITLE
Fix text overflow p element

### PR DESCRIPTION
**Pull request by vaniot-s**

### CODE REVIEW

**Comment by prologic** [comment]
@vaniot-s Did you forget a commit? I only see changes to `rice-box.go`? That's auto-generated.

**Comment by vaniot-s** [comment]
> @vaniot-s Did you forget a commit? I only see changes to `rice-box.go`? That's auto-generated.

I forget  it

**Comment by prologic** [comment]
No worries! 🤗 I'll happily review the next PR 😀

**Comment by vaniot-s** [comment]
> No worries!  I'll happily review the next PR

😀

**Pull request closed without merging**
