### PR TITLE
Add support for newlines in Twts (short-form) by using Unicode LS (\u2028) to encode them

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/backend

##### Test Plan

Tested locally:

Screen Shot 2020-09-05 at 08 46 40

The resulting feed is unchanged and will work with traditinoal clients:

```#!console
$ cat data/feeds/admin | tail
2020-09-03T15:16:05+10:00	(#<bxkbv2a http://10.0.0.109:8000/search?tag=bxkbv2a>) New Blog Post [Hello World!](http://10.0.0.109:8000/blog/admin/2020/09/03/hello-world) by @<admin http://10.0.0.109:8000/user/admin/twtxt.txt> 📝
2020-09-04T09:26:02+10:00	Hello World!
2020-09-04T09:26:15+10:00	Hello!
2020-09-04T12:30:20+10:00	Hello World :D
2020-09-04T18:55:30+10:00	Hello World! :D
2020-09-04T18:55:34+10:00	sdfasdf afdsafsd afds adfs
2020-09-04T18:55:36+10:00	dflasdfkjadfsjkh
2020-09-04T18:55:37+10:00	afdskasdfjkhasdfkhj
2020-09-05T08:32:13+10:00	This is a test Twt With multiple lines of text Hopefully this works as intended 😀 Without breaking the twtxt.txt spec 🤣
2020-09-05T08:33:49+10:00	This is a test Twt With multiple lines of text Hopefully this works as intended 😀 Without breaking the twtxt.txt spec 🤣
```

A client such as [Twet](https://github.com/quite/twet) renders a feed
with Unicode LS (`\u2028`) like this:

Screen Shot 2020-09-05 at 08 55 40

##### Additional Information

Resolved [this user feedback](https://twtxt.net/twt/sd7smfq)

### CODE REVIEW

**Review by lwojcik — DISMISSED** [review]

**Review by JsAppNinja — DISMISSED** [review]
looks good.

**Comment by prologic** [comment]
@lwojcik Did you approve this PR I can't tell from the Github (_sometimes shitty_) UI :)

**Review by prologic — COMMENTED** [review]
LGTM from me too! 😎

**Review by lwojcik — APPROVED** [review]
LGTM

**Comment by dbohdan** [comment]
I've had a different idea for backwards-compatible newlines that does not require Unicode input: when the client sees a sequence of twts with the same timestamp, join their text with a newline.  I don't know if it's worth implementing in twtxt.net alongside this feature, but I am leaving it here for whoever searches for "newlines in twtxt".

**Comment by prologic** [comment]
> I've had a different idea for backwards-compatible newlines that does not require Unicode input: when the client sees a sequence of twts with the same timestamp, join their text with a newline. I don't know if it's worth implementing in twtxt.net alongside this feature, but I am leaving it here for whoever searches for "newlines in twtxt".

Ahh that works nicely too and doesn't hurt compatibility. Want to raise this as a new feature?

**Comment by dbohdan** [comment]
@prologic All right.  I've written #215.

**Comment by prologic** [comment]
Oh! Wonderful I'll take a gander! Thanks! 🙇‍♂️

**Pull request merged**
