### PR TITLE
WIP: Add support for IndieAuth endpoint

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/backend

##### Test Plan

```#!sh
[twtxt] 2020/10/30 23:21:01 (2600:3c01::f03c:91ff:fe94:80b2) "GET /user/admin HTTP/1.1" 200 3752 6.027172ms
WARN[0012] error retrieving client information from https://indielogin.com/  error="error: no entry found"
INFO[0012] IndieAuth Authorization request for admin from indielogin.com
INFO[0012] Callback: "https://3deb1bfc9535.ngrok.io/user/admin/indieauth/callback?redirect_url=https://indielogin.com/redirect/indieauth&state=1930c13d10aceac67e117c35"
[twtxt] 2020/10/30 23:21:02 (2001:44b8:2181:c300:f80d:6f08:fb4d:ff69) "GET /user/admin/indieauth/auth?me=https%3A%2F%2F3deb1bfc9535.ngrok.io%2Fuser%2Fadmin&redirect_uri=https%3A%2F%2Findielogin.com%2Fredirect%2Findieauth&client_id=https%3A%2F%2Findielogin.com%2F&state=1930c13d10aceac67e117c35&response_type=id HTTP/1.1" 200 2894 1.046924125s
INFO[0016] u.String(): "https://indielogin.com/redirect/indieauth?code=QN0MiXG3A&state=1930c13d10aceac67e117c35"
[twtxt] 2020/10/30 23:21:06 (2001:44b8:2181:c300:f80d:6f08:fb4d:ff69) "GET /user/admin/indieauth/callback?redirect_url=https://indielogin.com/redirect/indieauth&state=1930c13d10aceac67e117c35 HTTP/1.1" 302 114 305.338µs
[twtxt] 2020/10/30 23:21:06 (2600:3c01::f03c:91ff:fe94:80b2) "POST /user/admin/indieauth/auth HTTP/1.1" 200 59 417.049µs
```

- Test public pod using [ngrok](https://ngrok.io)

Screen Shot 2020-10-30 at 11 20 56 PM

- Login to  https://pin13.net/login using my account

Screen Shot 2020-10-30 at 11 20 59 PM

- Approve the login

Screen Shot 2020-10-30 at 11 21 04 PM

- Success!

Screen Shot 2020-10-30 at 11 21 09 PM

##### Additional Information

Cloess #11 -- At least this satisfies the basics of providing an IndieAuth endpoint where users can now use their Twt.social / Twtxt "identity" to login to other websites that support IndieAuth.

We will expand support in the future as valid use-cases come up (_e.g: cross-pod features_)

### CODE REVIEW

**Comment by prologic** [comment]
cc @fluffy-critter

**Comment by fluffy-critter** [comment]
I don't know enough about your code or the frameworks you use to helpfully review this code. But you can test this by going to https://beesbuzz.biz/profile and then trying to sign in as a twtxt.net identity, and it should show you the identity you signed in as.

**Comment by prologic** [comment]
I don't need to build the token endpoint yet do I?

**Comment by fluffy-critter** [comment]
Token endpoint shouldn't be necessary for simple identity grants. Authl (the library used on my site) doesn't make use of it, in any case.

**Comment by prologic** [comment]
Okay well I'm not 100% happy with this implementation just yet, so you _might_ see some test logins from some [ngrok](https://ngrok.io) looking URIs from my local dev machine. Is that okay? :)

**Comment by fluffy-critter** [comment]
Sure, that's fine. I should probably spin up a public Authl test instead, for that sort of thing.

**Comment by fluffy-critter** [comment]
Oh actually you could just run the Authl test locally, too. :) It should be pretty straightforward as long as you have Python installed. https://github.com/PlaidWeb/Authl - just run `./test.sh` and the rest should be pretty obvious.

**Comment by prologic** [comment]
Can you add a `Dockerfile` and publish a Docker image on the [Docker Hub](https://hub.docker.com) That would make things _much_ easier for me :)

**Comment by fluffy-critter** [comment]
Sorry, I don't use Docker, which is *major* overkill for Authl's development test anyway. Authl isn't a standalone application, it's a library.

**Comment by prologic** [comment]
Oh I see, but you want me to use it as a standalone application and setup a Python development environment? 😀 (_I don't do much Python dev these days!_) 🤣

**Comment by fluffy-critter** [comment]
I was just suggesting using Authl's test environment as a standalone way to validate your login flow, because it's very easy to set up as a thing to test IndieAuth with. It's literally just:

```
git clone git@github.com:PlaidWeb/Authl.git
cd Authl
./test.sh
```

and then pointing your browser to http://localhost:5000/ to try logging in.

There are probably other things you can test against too. Or you can use a public-facing IndieAuth-based site, like the indieweb wiki or my personal website or whatever.

**Comment by prologic** [comment]
It's okay 😀 I'll work it out! Meanwhile I'm going to go get some fresh air 😎

**Pull request closed without merging**
