### PR TITLE
Fix footer layout regression

### PR DESCRIPTION
**Pull request by der-lyse**
Commit a974e082b9a884e0119939391aafc6f7f9038f59 caused a regression where the footer would not correctly be rendered as two boxes stacked on each other on small browser sizes. The footer content was always rendered in horizontally stacked boxes which looked like crap when there was not much horizontal space. [See this comment for a screenshot](https://github.com/jointwt/twtxt/pull/321#issuecomment-752348483).

The original behavior was flawed, too. Only very small browser sizes would work. Now we render it only horizontally, if the whole contents fits in a single line. Whenever we need more than one, we switch to vertical stacking. This obviously depends on the chosen font available on the system, so my selected width of 1200px may be a bit more conservative than necessary.

@prologic: I don't have a fancy pocket calculator to test this on, I just experimented with Firefox and Konqueror on my laptop. So I kindly ask you to verify this attempted fix on your mobile and other browsers you may have access to. :heart:

### CODE REVIEW

**Comment by prologic** [comment]
> @prologic: I don't have a fancy pocket calculator to test this on, I just experimented with Firefox and Konqueror on my laptop. So I kindly ask you to verify this attempted fix on your mobile and other browsers you may have access to. ❤️

Will do! 👍

**Comment by prologic** [comment]
It's better, but not perfect 😀

IMG_E3CEDEBCE210-1

**Review by prologic — DISMISSED** [review]

**Comment by der-lyse** [comment]
Well, just like before. :-/ I can reproduce this by zooming (to 170% in my particular environment) on twtxt.net, it's funny though, that in debug mode locally this doesn't happen. Instead it switches to stacking layout when reaching 170%. Weird, I have already some theories and will look into it.

**Comment by prologic** [comment]
I'll merge this anyway 😁

**Comment by prologic** [comment]
Can you resolve the conflicts first ? 😁

**Comment by der-lyse** [comment]
I fixed the conflict with the rice box. However, I didn't figure out yet what is going on with the CSS. It looks like the correct rules are applied by the browser, but I have no idea why it is rendered differently.

**Review by prologic — APPROVED** [review]

**Pull request merged**
