### PR TITLE
Add a fixed post button and hide the post form by default

### LINKED ISSUE #373: Collapse-able composition area
**Is your feature request related to a problem? Please describe.**
When monitoring my feed from the browser at 1080 resolution, there aren't enough individual feed entries visible for easy skimming. 

**Describe the solution you'd like**
I'd like to see the composition area made to be collapse-able. 

**Describe alternatives you've considered**
N/A

**Additional context**

https://twtxt.psynergy.io/media/RBDP7QzjKFQ4NrpLL3H7Ak

### PR DESCRIPTION
**Pull request by prologic**
This basically solves and fixes #373 (_I think_)

The way this work is simple:

- If your browser has javascript enabled, the `<postform>` is hidden by default and the new "Post" button fixed to the lower right unhides the postform and focuses it.
- Otherwise on browsers with javascript disabled or not available you just get the normal `<postform>` as it was before.

Basically this looks like this:

With Javascript:

Screen Shot 2021-02-12 at 23 30 52
Screen Shot 2021-02-12 at 23 30 55

Without Javascript:

Screen Shot 2021-02-12 at 23 31 35

### CODE REVIEW

**Comment by prologic** [comment]
Alternatives implementation:

Screen Shot 2021-02-13 at 00 07 59
Screen Shot 2021-02-13 at 00 08 01
Screen Shot 2021-02-13 at 00 08 03

**Comment by prologic** [comment]
Maybe add `role="button"`:

Screen Shot 2021-02-13 at 00 14 04

Opinions? 🤔 I'm _really_ not great at UI/UX 🤣 Can't you tell 😛 (@markwylde 👋)

**Comment by der-lyse** [comment]
I like the version without the `role=button` a lot better.

When activating the button to show the form, the page scrolls down right to the top of the textarea. However, the tool bar is "cut off" and people need to scroll up a bit in order to use it. I suggest scrolling down to the top of the toolbar instead. Alternatively it might be even better to not scroll at all. (Disclaimer: I've always used twtd for testing purposes only, never in production. I'm also only using it on a real screen, so I don't know how this would feel like for these tiny mobile thingies.)

**Comment by prologic** [comment]
I don't feel that the navbar solutions are any good IHMO. There's something that's a bit "off". It doesn't feel right based on using a lot of other "good" user interfaces with good UX. I dunno. I'm going to have to defer to someone with better UX skills than me :)

**Comment by der-lyse** [comment]
On another note: I never heard of the `<postform>` element, does this really exist?

When hiding the form by default, we maybe also want to consider adding a user setting, so they can revert to the old style, where the form is always shown. But real users have to say, whether they actually want this option or not.

**Comment by prologic** [comment]
> On another note: I never heard of the `<postform>` element, does this really exist?

No it isn't! But it's called HTML5 semantic web 😋

> When hiding the form by default, we maybe also want to consider adding a user setting, so they can revert to the old style, where the form is always shown. But real users have to say, whether they actually want this option or not.

Agreed.

**Comment by prologic** [comment]
@markwylde You got any good suggestions here? 🤔 Or are we reaching the limits of the CSS library we're using and the UX we started out with?

**Comment by prologic** [comment]
What about this:

Screen Shot 2021-02-13 at 10 03 50 PM
Screen Shot 2021-02-13 at 10 03 53 PM

**Comment by markwylde** [comment]
I'm not too sure. Having a think... I'm not really a fan of the big + at the bottom right, top right, as I normally miss it, thinking it's an advert or "Chat to our support" nonesense :P

Probably just me though. Let me ponder it.

**Comment by prologic** [comment]
Thanks @markwylde 😍

**Comment by der-lyse** [comment]
Nope, not just you, @markwylde. ;-) The ad blocker in my brain hides this, too. It took me literally several minutes to locate the button on the bottom right corner of the initial version.

Even though I agree with @prologic, that in the navigation at the top it kinda breaks with that established logic, it's screaming at you the least and also looks halfway decent. In my mind the big blue circle doesn't really fit in the rest of the appearance.

But there's probably an even better solution.

**Comment by adriangrigore** [comment]
I would just replace the post form with a "Twt" button that would expand to a form.

**Comment by markwylde** [comment]
I don't know, but the most I think about it, the more I think having the post box there all the time is okay.

I mean, fair enough it takes a lot of estate. But we could reduce it a bit?

image

**Comment by prologic** [comment]
@markwylde Love it! Maybe that's the solution is to just make it take up less real estate.

**Comment by prologic** [comment]
@markwylde In addition to the very nicely optimised post form you've proposed, how about we also in addition refactor thee top navbar a bit, ala GMail style:

Screen Shot 2021-02-16 at 11 43 28 PM

Where thee "Main Menu" becomes toggle-able with:

* Timeline
* Discover
* Feeds

With a big "+" glarring button where Gmail has it's "Compose" that toggles the postform's visibility?

**Comment by prologic** [comment]
Basically a contextual expandable/collapsible sidebar menu that can be used for "Social" and "Messages" views.

**Pull request closed without merging**
